apiVersion: apps/v1
kind: Deployment

metadata:
  name: django-app
  namespace: default
  labels:
    app: django-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app

  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: ${CI_REGISTRY_IMAGE}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

      imagePullSecrets:
        - name: regcred
