apiVersion: apps/v1
kind: Deployment

metadata:
  name: django-app
  namespace: default
  labels:
    app: django-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app

  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: registry.git.chalmers.se/courses/dit824/2021/group01/genre-recognition:$CI_COMMIT_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: django-app-loadbalancer-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
