apiVersion: apps/v1
kind: Deployment

metadata:
  name: django-app
  namespace: gitlab-managed-apps
  labels:
    app: django-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app

  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: registry.git.chalmers.se/courses/dit824/2021/group01/genre-recognition:$CI_COMMIT_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

      imagePullSecrets:
        - name: regcred
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx-ingress-controller
  namespace: gitlab-managed-apps
spec:
  rules:
  - host: 35.225.195.169.nip.io
    http:
      paths:
      - backend:
        serviceName: django-app-service
        servicePort: 8000
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "django-app-service"
  namespace: "gitlab-managed-apps"
  labels:
    app: "django-app"
spec:
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  selector:
    app: "django-app"
  type: "ClusterIP"
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: ingress-nginx-ingress-controller
# spec:
#   selector:
#     app: django-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8000
#   type: LoadBalancer

