apiVersion: apps/v1
kind: Deployment

metadata:
  name: django-app
  namespace: gitlab-managed-apps
  labels:
    app: django-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app

  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: registry.git.chalmers.se/courses/dit824/2021/group01/genre-recognition:$CI_COMMIT_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: gitlab-managed-apps
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: django-app
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress-nginx-ingress-controller
  namespace: gitlab-managed-apps
spec:
  rules:
    - http:
      paths:
        - path:
          backend:
            serviceName: django-app-service
            servicePort: 8000
          